### ISSUE TITLE
P134 example failing with v4.py StepByStep.train()

### ISSUE THREAD

**Issue by jdgh000** [dvgodoy/PyTorchStepByStep#49] opened 2024-06-24 07:59 UTC
Imported stepByStep v4.py

sbs_rnn=StepByStep(model, loss, optimizer)
sbs_rnn.set_loaders(train_loader, test_loader)
sbs_rnn.train(100) <----

this caused following fail:
/home/nonroot/sbs//ch8/ch8-p134-full-classificiation-model.py:25: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:276.)
  train_data = TensorDataset(torch.as_tensor(points).float(),torch.as_tensor(directions).view(-1,1).float())
Traceback (most recent call last):
  File "/home/nonroot/sbs//ch8/ch8-p134-full-classificiation-model.py", line 38, in <module>
    sbs_rnn.train(100)
  File "/home/nonroot/sbs//ch8/../stepbystep/v4.py", line 186, in train
    loss = self._mini_batch(validation=False)
  File "/home/nonroot/sbs//ch8/../stepbystep/v4.py", line 155, in _mini_batch
    mini_batch_loss = step_fn(x_batch, y_batch)
  File "/home/nonroot/sbs//ch8/../stepbystep/v4.py", line 99, in perform_train_step_fn
    yhat = self.model(x)
  File "/home/guyen/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/guyen/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 1 positional argument but 2 were given

**Comment by dvgodoy** [comment] 2024-06-24 09:59
Hi @jdgh000 ,

I tried reproducing the error in Chapter 8's notebook but it didn't raise the error you reported.
Could you please paste the whole content of `ch8-p134-full-classificiation-model.py` file so I can try to pinpoint what happened?

Best,
Daniel

**Comment by jdgh000** [comment] 2024-06-25 02:34
i looked at ipynb files and appears same. what i did is made some enhancement and literally moved few lines of code around. the one in ch8 should work in the attachment. 
[p134.tar.gz](https://github.com/user-attachments/files/15963700/p134.tar.gz)

**Comment by dvgodoy** [comment] 2024-06-25 09:45
Hi @jdgh000 ,

Thank you for providing your code.
I figured out the issue, it is in the `SquareModel` class, which I past below with two corrected lines.
The error was triggered because the `forward()` method was missing its `self` argument. Once this was fixed, it raised a different error because the linear layer was assigned to `self.classifiers` in the constructor while referred to as `self.classifier` in the `forward()` method.
By fixing these two small issues, training proceeds as expected.

Regarding the environment, I always test my code in Colab (like a "standard" environment since I trust Google will keep the env stable).

Best,
Daniel

```python
class SquareModel(nn.Module):
    def __init__(self, n_features, hidden_dim, n_outputs):
        super(SquareModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.n_features = n_features
        self.n_outputs = n_outputs
        self.hidden = None

        # Simple RNN

        self.basic_rnn = nn.RNN(self.n_features, self.hidden_dim, batch_first = True)
    
        # classifier to produce as many logits as outputs

        # Original
        # self.classifiers = nn.Linear(self.hidden_dim, self.n_outputs)
        # Fixed
        self.classifier = nn.Linear(self.hidden_dim, self.n_outputs)

    # Original
    # def forward(X):
    # Fixed
    def forward(self, X):
        # X is batch first (N,L,F)
        # output is (N,L,H)
        # final hidden state is (1,N,H)
        
        batch_first_output, self.hidden = self.basic_rnn(X)
        
        # only last item in sequence (N,1,H)

        last_output = batch_first_output[:, -1]
         
        # classifier will output (N,1,n_outputs)

        out = self.classifier(last_output)

        # final outputs is (N, n_outputs)
        return out.view(-1, self.n_outputs)
```

**Comment by jdgh000** [comment] 2024-06-26 06:34
thx!! it worked. good catch!

**Closed** 2024-06-26 06:34 UTC
